harbour-shutter.svg /usr/share/icons/hicolor/scalable/apps/
icons/86x86/harbour-shutter.png /usr/share/icons/hicolor/86x86/apps/
icons/108x108/harbour-shutter.png /usr/share/icons/hicolor/108x108/apps/
icons/128x128/harbour-shutter.png /usr/share/icons/hicolor/128x128/apps/
icons/172x172/harbour-shutter.png /usr/share/icons/hicolor/172x172/apps/
icons/172x172/harbour-shutter.png /usr/share/icons/
harbour-shutter.desktop /usr/share/applications/hildon/
